name: drugsense_ai
description: "DrugSense AI – Smart Medicine Identifier & Information Assistant"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # API calls
  http: ^1.2.1

  # Secure storage
  flutter_secure_storage: ^9.2.2

  # Image picker (ONLY HERE)
  image_picker: ^1.1.2

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true